### ISSUE TITLE
about_arrays missing result, expected, diff

### ISSUE THREAD

**Issue by TomMcCluskey** [liammclennan/JavaScript-Koans#47]
The About Arrays tests do not display  results, expected values, or diffs, unlike tests before and after.

![screenshot from 2015-02-24 14 25 50](https://cloud.githubusercontent.com/assets/3987881/6360761/5e7216a4-bc31-11e4-9fea-a88b346c6daa.png)

**Comment by sukhesh035** [comment]
Where is the javaScript code, you just wrote test cases.. I'm a bit confused. please let me know if you can, i can help you
