### ISSUE TITLE
[Error: object is not a function] message: 'object is not a function'

### ISSUE THREAD

**Issue by dashingly** [liammclennan/JavaScript-Koans#49]
I am getting following error when I am trying to run using IntelliJ IDEA or NodeJS Qunit plugin:
[Error: object is not a function] message: 'object is not a function'

**Comment by liammclennan** [comment]
JavaScript-Koans is not built to work that way. If you get it to work I'd be happy to consider a pull request.

**Comment by dashingly** [comment]
Any suggestions how to run it inside InterlliJ IDEA?

**Comment by liammclennan** [comment]
It is intended to be run inside a browser. Can IntelliJ host a browser?

On Tue, Apr 14, 2015 at 7:32 AM, Daniil Shevelev <notifications@github.com>
wrote:

> Any suggestions how to run it inside InterlliJ IDEA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liammclennan/JavaScript-Koans/issues/49#issuecomment-92507144>
> .
>



-- 
Liam McLennan.

liam@eclipsewebsolutions.com.au
http://www.eclipsewebsolutions.com.au

**Comment by dashingly** [comment]
Sorry, missed the instructions sentence that mentions "jskoans.htm". Thanks!

**Comment by liammclennan** [comment]
No problem. Enjoy!

On Tue, Apr 14, 2015 at 7:35 AM, Daniil Shevelev <notifications@github.com>
wrote:

> Sorry, missed the instructions sentence that mentions "jskoans.htm".
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liammclennan/JavaScript-Koans/issues/49#issuecomment-92508264>
> .
>



-- 
Liam McLennan.

liam@eclipsewebsolutions.com.au
http://www.eclipsewebsolutions.com.au
