### ISSUE TITLE
Expected results on topics/about_reflection.js

### ISSUE THREAD

**Issue by xrx** [liammclennan/JavaScript-Koans#53]
I'm wondering, what are the expected results on https://github.com/liammclennan/JavaScript-Koans/blob/master/topics/about_reflection.js#L58-L60

I get empty quotes, but i'm not sure if that is what expected, so I searched a little bit and based on https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Function/name I changed locally:

    var A = function() {
        this.aprop = "A";
    };

    var B = function() {
        this.bprop = "B";
    };

on top of that file to 

    function A() {
        this.aprop = "A";
    };

    function B() {
        this.bprop = "B";
    };    

And i get `"A"` as the expected `constructor.name` value, which makes more sense to me. If I'm wrong or missing sth. could you explain why?

**Comment by cytrowski** [comment]
This unfortunately depends on the browser you use. Open console in Chrome and Firefox and try the snippet below:

```
var x = function () {};
console.log(x.name);  // Chrome prints 'x' here; Firefox '' (empty quotes)
var y = function foo() {};
console.log(y.name); // Both Chrome and Firefox print 'foo' here
```


I believe this should not be in the Koans at all.

**Comment by liammclennan** [comment]
Agreed. I'm happy to take a PR.

**Comment by cytrowski** [comment]
No problem :) I'll make one later in the evening. Your Koans are great anyway ;)

**Comment by cytrowski** [comment]
Should we mark the issue closed?
