### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by UlisesGascon** [liammclennan/JavaScript-Koans#58]
Hi @liammclennan! I found this repository very useful and I've thought to translate it in Spanish language.

So, I will start to translate it now in [our fork](https://github.com/OSWeekends/JavaScript-Koans)... I will send you a pull request when is ready.

**Comment by UlisesGascon** [comment]
Pull request sent #59.

**Comment by liammclennan** [comment]
No response on the PR so closing.
